# Generated by Django 6.0.3 on 2026-06-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designparameters',
            name='slewing_ring_efficiency',
            field=models.FloatField(default=0.4, help_text='Slewing ring mechanical efficiency: 40%. Accounts for friction losses in the slewing ring drive mechanism.'),
        ),
        migrations.AlterField(
            model_name='designparameters',
            name='slewing_ring_ratio_pm401',
            field=models.FloatField(default=110.0, help_text='Slewing ring gear ratio: 110:1. Number of gearmotor revolutions per one full crane revolution. Source: TGB P26-04.'),
        ),
    ]
