# Generated by Django 6.0.3 on 2026-06-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(help_text='Supplier name or company', max_length=200)),
                ('motor_model', models.CharField(help_text='Motor model / type designation', max_length=300)),
                ('datasheet_source', models.CharField(blank=True, help_text='Source document or reference', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='General notes')),
                ('gear_series', models.CharField(blank=True, help_text='Gear series (e.g. helical bevel geared motor)', max_length=200)),
                ('gearmotor_output_speed_rpm', models.FloatField(blank=True, help_text='Gearmotor output speed (revolutions per minute)', null=True)),
                ('gearmotor_output_torque_nm', models.FloatField(blank=True, help_text='Gearmotor rated output torque (Newton-metres)', null=True)),
                ('gearbox_internal_ratio', models.FloatField(blank=True, help_text='Gearbox internal ratio (dimensionless)', null=True)),
                ('max_permissible_input_speed_rpm', models.FloatField(blank=True, help_text='Maximum permissible motor input speed (revolutions per minute)', null=True)),
                ('mounting_position', models.CharField(blank=True, help_text='Mounting position (e.g. M2, M4, M5)', max_length=100)),
                ('output_flange_description', models.CharField(blank=True, help_text='Output flange description', max_length=300)),
                ('output_shaft_description', models.CharField(blank=True, help_text='Output shaft specification', max_length=200)),
                ('keyway_standard', models.CharField(blank=True, help_text='Keyway standard', max_length=100)),
                ('painting_system', models.CharField(blank=True, help_text='Painting / corrosion protection system', max_length=100)),
                ('colour_ral', models.CharField(blank=True, help_text='Colour (RAL code)', max_length=50)),
                ('input_flange_description', models.CharField(blank=True, help_text='Input flange description', max_length=300)),
                ('housing_material', models.CharField(blank=True, help_text='Motor housing material', max_length=100)),
                ('duty_cycle', models.CharField(blank=True, help_text='Motor duty cycle (e.g. S3-25%)', max_length=50)),
                ('efficiency_class', models.CharField(blank=True, help_text='Motor efficiency class (e.g. IE2, IE3)', max_length=20)),
                ('motor_rated_power_kw', models.FloatField(blank=True, help_text='Motor rated power (kilowatts)', null=True)),
                ('motor_rated_speed_rpm', models.FloatField(blank=True, help_text='Motor rated speed (revolutions per minute)', null=True)),
                ('supply_voltage_v', models.CharField(blank=True, help_text='Supply voltage (Volts)', max_length=100)),
                ('supply_frequency_hz', models.CharField(blank=True, help_text='Supply frequency (Hertz)', max_length=50)),
                ('winding_connection', models.CharField(blank=True, help_text='Winding connection (Delta / Star)', max_length=50)),
                ('protection_class', models.CharField(blank=True, help_text='Degree of protection (IP class)', max_length=20)),
                ('terminal_box_position', models.CharField(blank=True, help_text='Terminal box mounting position', max_length=200)),
                ('cable_entries', models.CharField(blank=True, help_text='Cable entry thread sizes', max_length=200)),
                ('cooling_method', models.CharField(blank=True, help_text='Cooling method (IC designation)', max_length=100)),
                ('heater_spec', models.CharField(blank=True, help_text='Anti-condensation heater specification (Watts / Volts)', max_length=100)),
                ('total_weight_kg', models.FloatField(blank=True, help_text='Total weight of gearmotor (kilograms)', null=True)),
                ('certifications', models.CharField(blank=True, help_text='Certifications (CE, 3.1, UL, UKCA, etc.)', max_length=300)),
                ('temperature_range', models.CharField(blank=True, help_text='Ambient temperature range', max_length=100)),
                ('corrosivity_category', models.CharField(blank=True, help_text='Corrosivity category (C4, C5H, C5M, CX)', max_length=50)),
                ('rotation', models.CharField(blank=True, help_text='Direction of rotation', max_length=100)),
                ('starting_method', models.CharField(blank=True, help_text='Starting method', max_length=100)),
                ('heater_terminal_blocks', models.CharField(blank=True, help_text='Anti-condensation heater terminal block provision', max_length=200)),
                ('gearbox_structural_capacity_nm', models.FloatField(blank=True, help_text='Gearbox structural torque capacity (Newton-metres)', null=True)),
            ],
            options={
                'verbose_name': 'Motor Supplier',
                'verbose_name_plural': 'Motor Suppliers',
                'ordering': ['-updated_at'],
            },
        ),
    ]
