# Generated by Django 6.0.3 on 2026-05-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=255, unique=True)),
                ('model_name', models.CharField(max_length=500)),
                ('crane_type', models.CharField(choices=[('standard_pf', 'Standard PF'), ('pf_xxl', 'PF-XXL')], default='standard_pf', max_length=50)),
                ('motor_power', models.FloatField(help_text='kW')),
                ('motor_speed', models.FloatField(help_text='rpm')),
                ('motor_torque', models.FloatField(help_text='Nm')),
                ('motor_starting_torque', models.FloatField(blank=True, help_text='Nm max', null=True)),
                ('motor_starting_factor', models.FloatField(blank=True, help_text='Ma/Mn ratio', null=True)),
                ('motor_voltage_50hz', models.CharField(max_length=100)),
                ('motor_voltage_60hz', models.CharField(max_length=100)),
                ('motor_frame', models.CharField(max_length=100)),
                ('motor_flange', models.CharField(max_length=100)),
                ('motor_shaft', models.CharField(max_length=100)),
                ('motor_cooling', models.CharField(max_length=100)),
                ('motor_ip_rating', models.CharField(max_length=50)),
                ('motor_insulation_class', models.CharField(max_length=50)),
                ('motor_efficiency_class', models.CharField(max_length=50)),
                ('motor_ambient_temp_min', models.FloatField(blank=True, help_text='°C', null=True)),
                ('motor_ambient_temp_max', models.FloatField(blank=True, help_text='°C', null=True)),
                ('motor_heater', models.CharField(blank=True, max_length=100)),
                ('motor_coating', models.CharField(blank=True, max_length=100)),
                ('motor_color', models.CharField(blank=True, max_length=100)),
                ('motor_power_factor', models.FloatField(blank=True, null=True)),
                ('gearbox_model', models.CharField(max_length=255)),
                ('gearbox_ratio', models.FloatField()),
                ('gearbox_output_speed', models.FloatField(help_text='rpm')),
                ('gearbox_output_torque', models.FloatField(help_text='Nm')),
                ('gearbox_nominal_torque', models.FloatField(blank=True, help_text='Nm', null=True)),
                ('gearbox_starting_torque_max', models.FloatField(blank=True, help_text='Nm', null=True)),
                ('gearbox_tip_torque_max', models.FloatField(blank=True, help_text='Nm', null=True)),
                ('gearbox_efficiency_factor', models.FloatField(blank=True, help_text='CG factor', null=True)),
                ('gearbox_output_flange', models.CharField(max_length=100)),
                ('gearbox_output_shaft', models.CharField(max_length=100)),
                ('gearbox_oil_capacity', models.FloatField(blank=True, help_text='liters', null=True)),
                ('gearbox_oil_type', models.CharField(blank=True, max_length=255)),
                ('compliant', models.BooleanField(default=False)),
                ('compliance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_url', models.URLField(blank=True, help_text='Link to supplier datasheet')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motors', to='motors.motorsupplier')),
            ],
            options={
                'ordering': ['model_number'],
            },
        ),
    ]
