# Generated by Django 6.0.3 on 2026-06-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_motorcalculation_bevel_efficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcalculation',
            name='CF',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='M_Nenn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='Ma_Max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='Mk_Max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='Mk_Mn',
            field=models.FloatField(default=3.4),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='T_crane_lim',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='T_gm_start_MAX',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='eta_slew',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='gm_out_nom_nm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='gm_out_speed_rpm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='gm_out_start_nm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='i_slew',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='n_crane',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='overall_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_ambient_temp_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_ambient_temp_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_coating_ndft_um',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_coating_standard',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_fasteners',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_heater_vdc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_input_flange_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_motor_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_nameplate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_output_flange_coating',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_output_shaft_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_paint_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_shaft_length_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_shaft_seal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_surface_prep',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_voltage_400_50',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_voltage_400_60',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_voltage_480_60',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_voltage_690_50',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_voltage_690_60',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='motorcalculation',
            name='spec_cooling_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='motorcalculation',
            name='spec_duty_cycle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcalculation',
            name='spec_efficiency_class',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='motorcalculation',
            name='spec_frame_material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='motorcalculation',
            name='spec_insulation_class',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='motorcalculation',
            name='spec_ip_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='motorcalculation',
            name='spec_output_flange',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
