# Generated by Django 6.0.3 on 2026-06-23 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_motorcalculation_cf_motorcalculation_m_nenn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(help_text='Motor supplier (e.g., Watt Drive, Z:systems)', max_length=200)),
                ('model', models.CharField(help_text='Motor model (e.g., EP2557M)', max_length=200)),
                ('gm_type', models.CharField(blank=True, help_text='Geared-motor type designation', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('i_gb', models.FloatField(help_text='Gearbox reduction ratio')),
                ('n_mot', models.FloatField(help_text='Rated motor speed (rpm)')),
                ('P', models.FloatField(help_text='Rated motor power (kW)')),
                ('T_nom', models.FloatField(help_text='GM nominal output torque (Nm)')),
                ('T_pu', models.FloatField(blank=True, help_text='GM pull-up / acceleration torque (Nm)', null=True)),
                ('T_start', models.FloatField(help_text='GM start / breakaway torque (Nm)')),
                ('T_peak', models.FloatField(help_text='GM peak / max torque (Nm)')),
                ('T_in_max', models.FloatField(blank=True, help_text='Permissible gearbox input torque (Nm)', null=True)),
                ('T_bd', models.FloatField(blank=True, help_text='Motor breakdown torque (Nm)', null=True)),
                ('fB', models.FloatField(blank=True, help_text='Service factor', null=True)),
                ('duty', models.CharField(blank=True, help_text='Duty cycle (e.g., S2-12 min, S3-25%)', max_length=100)),
                ('flange', models.CharField(blank=True, help_text='Flange interface (e.g., □150 / Ø32 k6×50)', max_length=200)),
                ('voltage', models.CharField(blank=True, help_text='Supply voltage/frequency', max_length=100)),
                ('IP', models.CharField(blank=True, help_text='IP protection class', max_length=20)),
                ('insulation', models.CharField(blank=True, help_text='Insulation class', max_length=20)),
                ('heater', models.CharField(blank=True, help_text='Standstill heater', max_length=100)),
                ('temp', models.CharField(blank=True, help_text='Ambient temperature range', max_length=100)),
                ('coating', models.CharField(blank=True, help_text='Coating standard', max_length=100)),
                ('frame', models.CharField(blank=True, help_text='Frame material', max_length=100)),
                ('cooling', models.CharField(blank=True, help_text='Cooling method', max_length=100)),
                ('start_method', models.CharField(blank=True, default='DOL', help_text='Starting method (DOL, VFD, etc.)', max_length=100)),
                ('i_tot', models.FloatField(blank=True, help_text='Total reduction ratio = i_gb × i_slew', null=True)),
                ('n_gm', models.FloatField(blank=True, help_text='GM output speed (rpm)', null=True)),
                ('n_slew', models.FloatField(blank=True, help_text='Crane slewing speed (rpm)', null=True)),
                ('dP', models.FloatField(blank=True, help_text='Power consistency (fraction)', null=True)),
                ('M_S2', models.FloatField(blank=True, help_text='Ring running torque (Nm)', null=True)),
                ('M_PU', models.FloatField(blank=True, help_text='Ring pull-up torque (Nm)', null=True)),
                ('M_start', models.FloatField(blank=True, help_text='Ring start/breakaway torque (Nm)', null=True)),
                ('M_peak', models.FloatField(blank=True, help_text='Ring peak torque (Nm)', null=True)),
                ('checks_json', models.TextField(blank=True, default='{}', help_text='JSON dict of 11-point checks')),
                ('verdict', models.CharField(blank=True, choices=[('FITS', 'FITS (11/11)'), ('FITS_REVIEW', 'FITS — minor review'), ('DOES_NOT_FIT', 'DOES NOT FIT')], help_text='Final verdict', max_length=50)),
                ('passed_count', models.IntegerField(default=0, help_text='Number of checks passed (0-11)')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('standard_pf', 'PF Standard (ELW 597EM)'), ('pf_xxl', 'PF-XXL (TGB P26-04)')], max_length=20, unique=True)),
                ('ring_model', models.CharField(help_text='e.g., ELW 597EM or TGB P26-04', max_length=100)),
                ('i_slew', models.FloatField(help_text='Slewing-ring reduction ratio (i_slew)')),
                ('eta_slew', models.FloatField(default=0.4, help_text='Slewing-ring efficiency')),
                ('CF', models.FloatField(help_text='Combined factor = i_slew × η_slew')),
                ('M_max', models.FloatField(help_text='Ring maximum (structural) torque (Nm)')),
                ('M_rated', models.FloatField(help_text='Ring nominal/rated operating torque (Nm)')),
                ('n_slew_min', models.FloatField(help_text='Min crane slewing speed (rpm)')),
                ('n_slew_max', models.FloatField(help_text='Max crane slewing speed (rpm)')),
                ('n_slew_tgt', models.FloatField(help_text='Target crane slewing speed (rpm)')),
                ('n_gm_min', models.FloatField(help_text='Min GM output speed (rpm)')),
                ('n_gm_max', models.FloatField(help_text='Max GM output speed (rpm)')),
                ('k', models.FloatField(default=9549.3, help_text='Torque constant = 60000/(2π)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['system_type'],
            },
        ),
        migrations.DeleteModel(
            name='MotorCalculation',
        ),
        migrations.AddField(
            model_name='motor',
            name='ring_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motors', to='calculator.ringsystem'),
        ),
        migrations.AlterUniqueTogether(
            name='motor',
            unique_together={('ring_system', 'supplier', 'model')},
        ),
    ]
